name: Continuous Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: zip -r build.zip build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
