name: Move latest tag

on:
  push:
    branches:
      - main

jobs:
  move-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
